### PR TITLE
Update nodejs to 0.10.37 and npm to 2.7.3

### PR DESCRIPTION
**Pull request by abtris**

### CODE REVIEW

**Comment by abtris** [comment]
@fosrias Can be possible update nodejs and npm? Need for working with private registry.

**Comment by fosrias** [comment]
@abtris I will look at this and see why it is not passing. Thanks.

**Comment by fosrias** [comment]
@JackuB Could you work on this to get tests passing and this work with private npm. Thanks.

**Comment by fosrias** [comment]
@JackuB Please feel free to merge once tests are passing. I will leave to you to set the Accepted label. Presumably this will pass when you rebase against other PR.

**Pull request merged**
